language:
  node_js
sudo: false
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
before_script:
  - psql -c 'create database api-db;' -U postgres admin
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test