language: node_js
sudo: required
dist: trusty 
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_script:
  - psql -c "ALTER USER ;' -U postgres
script:
  - sudo -u postgres psql -c "..."
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test