language: node_js
sudo: required
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
services:
  - postgresql
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test
before_script:
  - psql -c 'CREATE DATABASE api-db;' -U postgres
  - psql -c 'CREATE USER postgres WITH PASSWORD 'admin';' -U postgres