language:
  node_js
sudo: false
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - ./node_modules/.bin/codecov
  - npm start test